extraSecret:
    - name: SECRET1
      value: ENC[AES256_GCM,data:nVsEDxvA,iv:74YHlLxuFNJt2NxtmtI4S23DnxK7pC1bh8L0p0VcEcA=,tag:YsXENrf/Gaem4uXSlv/pUw==,type:str]
    - name: SECRET2
      value: ENC[AES256_GCM,data:nIKzvFmS,iv:8fdlk0tb5zUu9i1Z0T/ulWUdCmv16X9QXO9SuouB6Xw=,tag:aq55csjYsG0jwbfAUtcpGA==,type:str]
sops:
    lastmodified: "2025-10-15T08:41:23Z"
    mac: ENC[AES256_GCM,data:kq8XLby9H2gTsa/VoInjaiD8YUA8G+ClJkIpz74sZs9Mu/oDSQeJJB82lS02nZkF9xJElw8gTDOsdPUn2pE+dXTdMZcfjpSwuo3jqLVkYY3NIu2f7dZfSiJfQS3LdqDQKSInTr19hgy41Fma+jysgoLFKOFui5OQ9qycAnsl3Wk=,iv:GPztXGf63fbkTxhSnd3NFwPtZveEkTxH0ueSBXwANtk=,tag:7xO3jeUs4Vmfa8ljhn5CPg==,type:str]
    pgp:
        - created_at: "2025-09-09T15:02:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DI42jIJV8G60SAQdA0pspkcndm+MafXsjGkbBpKnDXoO9K+2AzaTQ2tvgPm8w
            XKN7DQQOqxnEhH3fBQheCtzOw1ETsAqvmBQa17BgGDKIyo0c7f4iPztZAwCaZHt+
            0lwBS4MGi9y6d4ymA+SpUQ3xwB4/R8eUYfuK9RRbXeAWUjweTqv+kS+FEwOiZGCl
            3HzkWXIqIGPNK9oBNx5eb7SYEfJGeZbSDiZjeniwTZ+XXb/8oL4aExcsn5+7PQ==
            =jG/H
            -----END PGP MESSAGE-----
          fp: D8D2DA5830D4E298FE3D1DDC2A2BD78411EC59AB
        - created_at: "2025-09-09T15:02:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA0164Ys/d1ayAQv/SusRzzdAxqXH3S7kneRjE7l/wqBJnMKeiAWl3RwuWn51
            XEZRk3XRAiHsIWASdX4XzlQGlr1Sucl1X/1PbwEDmUfsjOHiYPyQlGB9/h+pg+jT
            apPfhzkJ/DN8Qq5ytHeeIeJi94lTTOcxrwv4xllA7NziGiokHT3zK9boWEeMXv8F
            R6gZaLCoit7IPpuRaTr5zkCkXnHWq3JyELk6iCxA4pKLWdSq2XeZ8CyqjTpMDjaa
            GeePltCnyJf0uoWRFosHzNieYV7W7QFAsTGBqAOZXYdZqPwftQx2nkbdV6PEJm2I
            fCLVDbIPiIpb6Yv86Mmc+McFMa/v+rtWxA7ZJ00jxFB83or8DRM/q1g28jSvlN6p
            an4sutNZZCVtR01VE85c6TYdItCDx/KplEYBny2RJSq4a2fd5NxS8FR27u/0DEUP
            r/637+jKP612d3SBq7Egz4aGrf7jsCAEB9dPR+Pqf20l6vVb7hlZxSmfK1Hradu6
            EwejTQ05X48ep+42DNgM0lwB3lbk8CJ4paD2jkjf6arWgLRaM6xGrzs1MOaiI0al
            YW4lEpez2z/3w43pbhiXIy0/mPD6mtN7g9SAWcMn3K7mXVfADJ2hwfbBPqBvaNxR
            3nwZXSV6Pdnl5ur35w==
            =oeF7
            -----END PGP MESSAGE-----
          fp: 53A6E93CDE871BD14A6A5BDDBDA8E91A74EF3FFA
        - created_at: "2025-09-09T15:02:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA4UQ0Dcua2DqAQgAhnmHv7xn1T1Yb+LpvdES+58PfagxMHkoxtTqZLExkxys
            i62EeZyfXu3dqCPlwNSRjmqTUwd0dExdjE3qwSmApNimTuWSdAeoH3eJfJdandr9
            P1UlkZ1QkSHRAcyvKSrFCYQnTS5DusBvNamvpD389knAcnsH8Xr7o/4T8n93TzZ5
            O+8QOvOt7JL1MbjBCxQ/pgmfzMwWiV2kYTfImyy5oGo9eCajn/Z2tAzRVkU9HAhn
            eIIbGUDtJ5ot6uKsIS181pjHzlJeZ9qufIKstRMvs3jkEWFQQN9zxK9ShgjQfMhG
            0p9umvlF2+WlJZ+g1LjObA70ppwmhgS/i+ZsyCKJx9JcAd/cBsVF74RqpIFCkzPJ
            OD3Jk5Tdpk/6KI5zBmNt1s6p10RK34N3tDUumNEQ5dBOsXQWGUs8RgYiT8fURJYr
            h+xkFigw6zLMPIOKbMcbAmrrmE8YNItLA3BMeM4=
            =ASpa
            -----END PGP MESSAGE-----
          fp: 5BEC26EEB1927F818C1DD9DBF3D47FF73ED265FF
    unencrypted_regex: ^name$
    version: 3.10.2
