podAnnotations:
  sidecar.opentelemetry.io/inject: "opentelemetry/otel-collector-sidecar"
  instrumentation.opentelemetry.io/inject-nodejs: "opentelemetry/instrumentation-js"

ingress:
  nginx:
    enabled: false
    className: "nginx"
    # annotations:
    #   nginx.ingress.kubernetes.io/server-snippet: |
    #     location = /robots.txt {
    #       add_header Content-Type text/plain;
    #       return 200 'User-agent: *\nDisallow: /\n';
    #     }
    #   nginx.ingress.kubernetes.io/proxy-body-size: 10M
      # nginx.ingress.kubernetes.io/whitelist-source-range: 158.160.116.237/32
    hosts:
      - host: application_name.mygig.ru
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: cert-applications-mygig-ru
        hosts:
          - application_name.mygig.ru

resources:
  requests:
    memory: "100M"
    cpu: "100m"
  limits:
    memory: "100M"

deploy_to: "production"
